### Урок 4.4: дополнительные концепции `NumPy`

In [2]:
import numpy as np

### Вычисления

Создадим массив `M` из последовательности чисел (вспомним про `arange()`):

In [3]:
M = np.arange(1, 10, 0.003)
M

array([1.   , 1.003, 1.006, ..., 9.991, 9.994, 9.997])

Округление:

In [4]:
np.round(M)  # до целого

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [5]:
np.round(M, 1)  # до 1го знака 

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [6]:
np.round(M, 2)

array([ 1.  ,  1.  ,  1.01, ...,  9.99,  9.99, 10.  ])

Возьмём массив поинтереснее с точки зрения округления:

In [7]:
A = np.array([2.5, 2.7, 8.1, 9.25])
A

array([2.5 , 2.7 , 8.1 , 9.25])

In [8]:
np.floor(A)  # в меньшую сторону

array([2., 2., 8., 9.])

In [9]:
np.ceil(A)  # в большую сторону

array([ 3.,  3.,  9., 10.])

Добавим ко всем элементам `A` 2:

In [49]:
np.add(A, 2)

array([ 6.23 ,  8.67 ,  9.2  , 11.181,  4.55 ])

А теперь вычтем 1:

In [11]:
np.subtract(A, 1)

array([1.5 , 1.7 , 7.1 , 8.25])

Суммируем все значения:

In [12]:
np.sum(A)

22.55

Или найдём их произведения:

In [13]:
np.prod(A)

505.74375

### Объекты `Datetimes` 

Попробуем сравнить две даты, сохранённые как строки:

In [15]:
d1 = "2019-02-25"
d2 = "2019-02-28"

In [16]:
d2 - d1  # нет

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Не получилось и это ожидаемо: нельзя из одного текста вычесть другой. Как быть? Превратить строку в специальный объект дата-время, который можно сравнивать с другими датами, считать, сколько времени прошло и так далее. В библиотеке `NumPy` такой объект есть:

In [20]:
start = np.datetime64(d1)

Зададим `finish` и проверим, что теперь даты можно сравнивать и получать разницу в днях (и не только):

In [21]:
finish = np.datetime64(d2)

In [22]:
finish - start

numpy.timedelta64(3,'D')

Итак, с момента `start` до момента `finish` прошло три дня.