In [1]:
import numpy as np

<h2><center>---=== Lesson 10.1 ===---</center></h2> 

In [2]:
scores = np.array([3, 5, 7, 9, 8, 10])

In [27]:
pairs = scores.reshape(3, 2)
pairs

array([[4, 5],
       [7, 9],
       [8, 7]])

In [7]:
pairs.ndim

2

In [8]:
scores.ndim

1

In [9]:
scores.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [13]:
t = pairs.transpose()
t

array([[ 3,  7,  8],
       [ 5,  9, 10]])

In [12]:
t.ravel()

array([ 3,  7,  8,  5,  9, 10])

<h2><center>---=== Lesson 10.2 ===---</center></h2>

In [15]:
pairs

array([[ 3,  5],
       [ 7,  9],
       [ 8, 10]])

In [17]:
pairs[0][0] = 3
pairs

array([[ 3,  5],
       [ 7,  9],
       [ 8, 10]])

In [19]:
pairs2 = pairs

In [21]:
pairs2[0][0] = 4
print(pairs2)
print(pairs)

[[ 4  5]
 [ 7  9]
 [ 8 10]]
[[ 4  5]
 [ 7  9]
 [ 8 10]]


In [23]:
pairs3 = pairs2.copy()
pairs3[2][1] = 9
print('pairs2:', pairs2)
print('pairs3:', pairs3)

pairs2: [[ 4  5]
 [ 7  9]
 [ 8 10]]
pairs3: [[4 5]
 [7 9]
 [8 9]]


In [32]:
pairs4 = pairs[:]
pairs4[2][1] = 0
print(pairs4)

[[4 5]
 [7 9]
 [8 0]]


In [33]:
print('pairs:', pairs)

pairs: [[4 5]
 [7 9]
 [8 0]]


In [34]:
pairs[1][1] = 3
pairs

array([[4, 5],
       [7, 3],
       [8, 0]])

In [35]:
pairs4

array([[4, 5],
       [7, 3],
       [8, 0]])

In [36]:
pairs[0:2]

array([[4, 5],
       [7, 3]])

In [37]:
pairs[0:2] = [[5, 4], [9, 7]]
pairs

array([[5, 4],
       [9, 7],
       [8, 0]])