In [1]:
import numpy as np

In [14]:
zero = np.zeros((5))
zero

array([0., 0., 0., 0., 0.])

In [15]:
zero.ndim

1

In [4]:
matrix = np.arange(0, 50)

In [6]:
matrix.reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
matrix.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
matrix.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
matr = matrix.reshape(25, 2)
matr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [21]:
matr.ndim

2

In [23]:
matr.size

50

In [25]:
matr[7][0]

14

In [32]:
M = np.arange(1,3, 0.03)
M

array([1.  , 1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3 ,
       1.33, 1.36, 1.39, 1.42, 1.45, 1.48, 1.51, 1.54, 1.57, 1.6 , 1.63,
       1.66, 1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.87, 1.9 , 1.93, 1.96,
       1.99, 2.02, 2.05, 2.08, 2.11, 2.14, 2.17, 2.2 , 2.23, 2.26, 2.29,
       2.32, 2.35, 2.38, 2.41, 2.44, 2.47, 2.5 , 2.53, 2.56, 2.59, 2.62,
       2.65, 2.68, 2.71, 2.74, 2.77, 2.8 , 2.83, 2.86, 2.89, 2.92, 2.95,
       2.98])

In [38]:
M.round(1)

array([1. , 1. , 1.1, 1.1, 1.1, 1.2, 1.2, 1.2, 1.2, 1.3, 1.3, 1.3, 1.4,
       1.4, 1.4, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6, 1.6, 1.7, 1.7, 1.7, 1.8,
       1.8, 1.8, 1.8, 1.9, 1.9, 1.9, 2. , 2. , 2. , 2.1, 2.1, 2.1, 2.1,
       2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5,
       2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8, 2.8, 2.9, 2.9, 2.9,
       3. , 3. ])

In [39]:
A = np.arange(1, 3, 0.3)
A

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [40]:
np.floor(A)

array([1., 1., 1., 1., 2., 2., 2.])

In [41]:
np.ceil(A)

array([1., 2., 2., 2., 3., 3., 3.])

In [44]:
np.add(A, 2)

array([3. , 3.3, 3.6, 3.9, 4.2, 4.5, 4.8])

In [46]:
A1 = A * 2
A1

array([ 4. ,  5.2,  6.4,  7.6,  8.8, 10. , 11.2])

In [47]:
np.subtract(A1, 2)

array([2. , 3.2, 4.4, 5.6, 6.8, 8. , 9.2])

In [48]:
np.sum(A1)

53.2

In [49]:
np.prod(A1)

997143.3472000003

In [60]:
today = '2020-02-25'
birthday = '1985-11-14'

In [61]:
today = np.datetime64(today)
birthday = np.datetime64(birthday)

In [57]:
my_age = (today - birthday)/365
my_age

numpy.timedelta64(34,'D')

In [66]:
week = np.array([('Monday', 7, 82.2), 
                 ('Tuesday', 8, 82.0), 
                 ('Wednesday', 9, 81.8), 
                 ('Thursday', 7, 81.2), 
                 ('Friday', 8, 80.5)], 
dtype=[('day', 'U10'), 
       ('wakeup', int), 
       ('weight', float)])

week

array([('Monday', 7, 82.2), ('Tuesday', 8, 82. ), ('Wednesday', 9, 81.8),
       ('Thursday', 7, 81.2), ('Friday', 8, 80.5)],
      dtype=[('day', '<U10'), ('wakeup', '<i4'), ('weight', '<f8')])

In [72]:
week[['day', 'wakeup']]

array([('Monday', 7), ('Tuesday', 8), ('Wednesday', 9), ('Thursday', 7),
       ('Friday', 8)],
      dtype={'names':['day','wakeup'], 'formats':['<U10','<i4'], 'offsets':[0,40], 'itemsize':52})

In [73]:
week[['day', 'weight']]

array([('Monday', 82.2), ('Tuesday', 82. ), ('Wednesday', 81.8),
       ('Thursday', 81.2), ('Friday', 80.5)],
      dtype={'names':['day','weight'], 'formats':['<U10','<f8'], 'offsets':[0,44], 'itemsize':52})

In [77]:
week['weight'][1]

82.0

In [82]:
week[3] = ('Thursday',10, 81.4)

In [83]:
week

array([('Monday',  7, 82.2), ('Tuesday',  8, 82. ),
       ('Wednesday',  9, 81.8), ('Thursday', 10, 81.4),
       ('Friday',  8, 80.5)],
      dtype=[('day', '<U10'), ('wakeup', '<i4'), ('weight', '<f8')])

In [85]:
week[2]['wakeup'] = 5

In [87]:
week['wakeup'][2] = 4
week

array([('Monday',  7, 82.2), ('Tuesday',  8, 82. ),
       ('Wednesday',  4, 81.8), ('Thursday', 10, 81.4),
       ('Friday',  8, 80.5)],
      dtype=[('day', '<U10'), ('wakeup', '<i4'), ('weight', '<f8')])

In [88]:
np.save('week.npy', week)

In [90]:
load = np.load('week.npy')
print(load)

[('Monday',  7, 82.2) ('Tuesday',  8, 82. ) ('Wednesday',  4, 81.8)
 ('Thursday', 10, 81.4) ('Friday',  8, 80.5)]


In [93]:
numbers = np.arange(1, 21, 0.01)
np.savetxt('numbers.txt', numbers)

In [97]:
np.loadtxt('numbers.txt')

[ 1.    1.01  1.02 ... 20.97 20.98 20.99]


In [99]:
string = np.array2string(numbers)
string

'[ 1.    1.01  1.02 ... 20.97 20.98 20.99]'

In [101]:
np.savetxt('numbers.txt', string)

ValueError: Expected 1D or 2D array, got 0D array instead

In [102]:
my_list = numbers.tolist()

In [103]:
np.savetxt('numbers.txt', my_list)