In [1]:
import numpy as np

In [17]:
zero = np.zeros((3, 3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
one = np.ones((3, 3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
eye = np.eye((3))
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
_ = eye + one
_

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [28]:
mult = _ ** 2
mult

array([[4., 1., 1.],
       [1., 4., 1.],
       [1., 1., 4.]])

In [29]:
mult[1].fill(5)
mult

array([[4., 1., 1.],
       [5., 5., 5.],
       [1., 1., 4.]])

In [30]:
mult[1][1] = 3
mult

array([[4., 1., 1.],
       [5., 3., 5.],
       [1., 1., 4.]])

In [31]:
mult[2, 0] = 6
mult[0][1] = 2
mult[1][2] = 7
mult

array([[4., 2., 1.],
       [5., 3., 7.],
       [6., 1., 4.]])

In [36]:
mult.mean(axis = 1)

array([2.33333333, 5.        , 3.66666667])

In [38]:
mult_super = mult * mult
mult_super

array([[16.,  4.,  1.],
       [25.,  9., 49.],
       [36.,  1., 16.]])