In [2]:
import numpy as np

In [3]:
np.log(4)

1.3862943611198906

In [5]:
np.mean([20, 40, 30, 450, 45, 30])

102.5

In [6]:
np.median([20, 40, 30, 450, 45, 30])

35.0

In [7]:
np.array([2, 3, 4])

array([2, 3, 4])

In [8]:
np.array([[5, 2, 3.5],
         [1, 9, 6.5]])

array([[5. , 2. , 3.5],
       [1. , 9. , 6.5]])

In [9]:
np.array([[[6, 3],
           [6,8]],
          [[1,0],
          [0, 1]]])

array([[[6, 3],
        [6, 8]],

       [[1, 0],
        [0, 1]]])

In [11]:
np.array([[0, 0, 1],
        [0, 1]])

array([list([0, 0, 1]), list([0, 1])], dtype=object)

In [12]:
np.array([[5, 8.2], [1, 2]])

array([[5. , 8.2],
       [1. , 2. ]])

In [13]:
np.array([['Victor', 'Ann'], [23, 24]])

array([['Victor', 'Ann'],
       ['23', '24']], dtype='<U6')

In [ ]:

                            ---===Lesson 9.3===---


In [16]:
turnout = np.array([0.62, 0.43, 0.79, 0.56])
turnout

array([0.62, 0.43, 0.79, 0.56])

In [18]:
np.array([2, 3, 8]) + np.array([7, 4, 3])

array([ 9,  7, 11])

In [19]:
week1 = np.array([4000, 0, 2000, 0, 1200])
week2 = np.array([1000, 2000, 0, 0, 3500])

In [20]:
week1 + week2

array([5000, 2000, 2000,    0, 4700])

In [22]:
(week1 + week2) / 2

array([2500., 1000., 1000.,    0., 2350.])

In [24]:
np.array([2, 3]) ** 2

array([4, 9], dtype=int32)

In [ ]:

                            ---===Lesson 9.4===---


In [26]:
m = np.array([[2, 5],
              [6, 8],
              [1, 3]])

In [27]:
m

array([[2, 5],
       [6, 8],
       [1, 3]])

In [28]:
m.ndim

2

In [29]:
m.shape

(3, 2)

In [30]:
m.size

6

In [31]:
m[1][0]

6

In [32]:
m[1][1]

8

In [33]:
m[1, 1]

8

In [34]:
m[2, 3]

IndexError: index 3 is out of bounds for axis 1 with size 2

In [35]:
m[2]

array([1, 3])

In [36]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [37]:
m[1:]

array([[6, 8],
       [1, 3]])

In [38]:
m[:1]

array([[2, 5]])

In [39]:
m[:]

array([[2, 5],
       [6, 8],
       [1, 3]])

In [41]:
m[0:3:2]

array([[2, 5],
       [1, 3]])

In [42]:
m[::2]

array([[2, 5],
       [1, 3]])

In [43]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

In [ ]:

                            ---===Lesson 9.5===---


In [45]:
marks = np.array([5, 4, 3, 5, 4, 3, 4])

In [46]:
marks.min()

3

In [47]:
marks.max()

5

In [49]:
marks.mean()

4.0

In [50]:
marks.argmax()

0

In [51]:
marks.argmin()

2

In [53]:
grades = np.array([[3, 5, 5, 4, 3],
                   [3, 3, 4, 3, 3], 
                   [5, 5, 5, 4, 3]])

In [54]:
print(grades)

[[3 5 5 4 3]
 [3 3 4 3 3]
 [5 5 5 4 3]]


In [55]:
grades.mean(axis = 1)

array([4. , 3.2, 4.4])

In [56]:
grades.mean(axis = 0)

array([3.66666667, 4.33333333, 4.66666667, 3.66666667, 3.        ])

In [ ]:
                            ---===Lesson 9.6===---

In [57]:
np.array([10.5, 45, 2])

array([10.5, 45. ,  2. ])

In [59]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

In [60]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [61]:
np.arange(2, 9, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5])

In [63]:
z = np.zeros((3, 3))

In [65]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
o = np.ones((2, 4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
e = np.eye((5))
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:

                             ---===Lesson 9.7===---
    

In [75]:
a = 6
b = 9

In [76]:
b > a

True

In [77]:
b >= a

True

In [78]:
a == b

False

In [90]:
ages = np.array([[15, 23, 32, 45, 52],
                [68, 34, 12, 78, 20],
                [25, 67, 33, 45, 14]])

In [87]:
M = ages >= 16
M

array([[False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False]])

In [95]:
work = (ages > 18) & (ages < 60)
work

array([[False,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True, False]])

In [96]:
work.sum()

9

In [97]:
(ages < 18) | (ages > 60)

array([[ True, False, False, False, False],
       [ True, False,  True,  True, False],
       [False,  True, False, False,  True]])

In [98]:
ages[ages >= 16]

array([23, 32, 45, 52, 68, 34, 78, 20, 25, 67, 33, 45])

In [100]:
ages[(ages >= 16) & (ages < 60)]

array([23, 32, 45, 52, 34, 20, 25, 33, 45])